### ISSUE TITLE
Sensor  unique ID is missing

### ISSUE THREAD

**Issue by frantisek007** [domen-jersek/PoKeys_HomeAssistant_plugin#1]
Hi 
I have an error:
This entity ('sensor.pokeys57e_device_1_pokeys_easysensor_temperature_vonku') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

without unique ID I cannot create a thermostat according this temperature sensor.
If I add unique_id manually in yaml than HA says it is not defined.
any advice?
Thank you.
Regards,
Frantisek

**Comment by domen-jersek** [comment]
Hi,
Could you plese eloborate (paste the full error, paste your yaml configuration, the model of your sensor, the sensor index in the pokeys app)? Do you have any other entities with the id "pokeys57e_device_1_pokeys_easysensor_temperature_vonku"? Its strange since the plugin should automatically create unique ids.
Kind regards,
Domen

**Comment by frantisek007** [comment]
Hi, thank you for your response.
sensors are all: ds18b20
[image: image.png]


[image: image.png]
[image: image.png]

Entities card:
type: entities
entities:
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_6
    name: KupelnaHore
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_2
    name: ChodbaDole
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_5
    name: ChodbaHore
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_7
    name: SpalnaHore
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_1
    name: Obyvacka
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_4
    name: Detska
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature_3
    name: KupelnaDole
  - entity: sensor.pokeys57e_device_1_pokeys_easysensor_temperature
    name: Vonku
title: DomLL

**Comment by domen-jersek** [comment]
You could try changing the yaml format to the one thats in the readme file.
`

pokeys:
    devices:
        - name: "PoKeys57E device 1"
           serial: 31557 #the serial number of your pokeys device
           sensors:
               - name: "pokeys easysensor temperature"
                  id: 0 #sensor id/index     

`
and the ids should be created automatically. However i cant confirm that it will work since i only tested the i2c sensors and dont have any ds18b20 that would allow me to implement the support.

**Comment by frantisek007** [comment]
Hi,

2024-10-14 20:47:03.911 WARNING (MainThread) [homeassistant.helpers.frame]
Detected that custom integration 'pokeys' accesses hass.helpers.discovery.
This is deprecated and will stop working in Home Assistant 2024.11, it
should be updated to import functions used from discovery directly at
custom_components/pokeys/__init__.py, line 436:
hass.helpers.discovery.load_platform("switch", DOMAIN, {}, config), please
create a bug report at
https://github.com/domen-jersek/PoKeys_HomeAssistant_plugin/issues

Regards,
Frantisek

**Comment by frantisek007** [comment]
Hi pokeys do nôt Work anymore in ha:Logger: homeassistant.setupSource: setup.py:497First occurred: 5:21:45 PM (1 occurrences)Last logged: 5:21:45 PMUnable to prepare setup for platform 'pokeys.sensor': Platform not found (cannot import name 'DEVICE_CLASS_HUMIDITY' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).On 10.10.2024, at 17:27, domen-jersek ***@***.***> wrote:﻿
You could try changing the yaml format to the one thats in the readme file.
pokeys: devices: - name: "PoKeys57E device 1" serial: 31557 #the serial number of your pokeys device sensors: - name: "pokeys easysensor temperature" id: 0 #sensor id/index     
and the ids should be created automatically. However i cant confirm that it will work since i only tested the i2c sensors and dont have any ds18b20 that would allow me to implement the support.
